### PR TITLE
Fix catalan typo

### PR DESCRIPTION
**Pull request by elboletaire**
I'm not sure how should I edit/regenerate the .mo file.. if I open the .po file with an editor like poedit, all the strings are moved around and doesn't look good.

### CODE REVIEW

**Comment by millert** [comment]
Translations for sudo are done by teams at https://translationproject.org/.  Please report this to the Catalan translation team, https://translationproject.org/team/ca.html.  This change can't be merged directly since it would simply be overwritten the next time we sync with translationproject.org.

**Comment by elboletaire** [comment]
Hhhmmm.... how? Should I send an e-mail directly to the translator? I don't see any way to notify there an issue.

**Comment by millert** [comment]
There is an email address for the translation team on that web page, or you could email the last translator of the sudoers module directly.

**Comment by elboletaire** [comment]
Yep.. I sent an e-mail to the mailing list for catalan. I hope that's the way.

**Comment by elboletaire** [comment]
omfg.. the mailing address for catalan bounces saying it does not exist...

**Pull request closed without merging**
