### PR TITLE
Adding regex command argument support and some insults

### PR DESCRIPTION
**Pull request by edneville**
This PR is to enable regex support of command line arguments (and a couple of new insults).

It will add syntax like the following:

```
       %containers ALL = /usr/bin/docker \
           m{(run|exec)\\s+-it?\\s+[^\\s]+\\s+/bin/bash}
```

### CODE REVIEW

**Comment by Cropi** [comment]
What is the status of this PR? Is the implementation done?

Is it going to be merged into master?

**Comment by edneville** [comment]
Hello @millert, what are your thoughts?

**Comment by LothaireCliquennois** [comment]
When is this PR going to be released ?

**Comment by b-a-t** [comment]
Any progress on this? `sudo` should have support for regex for at least 20 years for now.

**Comment by TylerReese** [comment]
@edneville @Cropi @LothaireCliquennois @b-a-t @michael-o, 1.9.10b1 has been released which now includes support for using regular expressions in the sudoers file, https://www.sudo.ws/releases/devel/#1.9.10b1.

**Pull request closed without merging**
